apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      version: v1
  template:
    metadata:
      labels:
        app: php
        version: v1
    spec:
      containers:
        - name: container-1
          image: swr.ap-southeast-3.myhuaweicloud.com/mysqldemo1/webserver:v1.0 
          env:
            - name: servername
            value: "mysql"
            - name: password
            value: "my-secret-pw"
            - name: dbname
            value: user_auth
            - name: username
            value: root
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: php
              readOnly: false
              mountPath: /var/www/html
      imagePullSecrets:
        - name: default-secret
      volumes:
        - name: php
          persistentVolumeClaim:
            claimName: php

---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: default
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate:         
        '{
            "type": "public",
            "bandwidth_name": "cce-php",
            "bandwidth_chargemode": "bandwidth",
            "bandwidth_size": 5,
            "bandwidth_sharetype": "PER",
            "eip_type": "5_bgp"
        }'
spec:
  selector:
    app: php
  externalTrafficPolicy: Cluster
  ports:
    - name: cce-service-0
      targetPort: 80
      nodePort: 0
      port: 8080
      protocol: TCP
  type: LoadBalancer