apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: v1
  template:
    metadata:
      labels:
        app: mysql
        version: v1
    spec:
      containers:
        - name: container-1
          image: mysql:latest
          envFrom:
            - configMapRef:
                name: auth-config
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 512Mi
      imagePullSecrets:
        - name: default-secret
  serviceName: mysql

---
  
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
    version: v1
spec:
  selector:
    app: mysql
    version: v1
  clusterIP: None
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
kind: Service  
metadata:
  name: mysql-nodeport 
  namespace: default
  labels:
    app: mysql #workload name 
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 3306 #service port
      targetPort: 3306 #container port
      nodePort: 30580 # Node port
  selector:
    app: mysql #workload name 

  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
